pastebinapp/urls.py
from django.conf.urls import url

from . import views

app_name='pastebinapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # // ex. /5
    url(r'^(?P<snip_id>[0-9]+)/$', views.code, name='code'),
    # // ex. /edit_snip/5
    url(r'^edit_snip/(?P<snip_id>[0-9]+)/$', views.edit_snip, name='edit_snip'),
    # // ex. /enter_snip
    url(r'enter_snip', views.enter_snip, name='enter_snip'),
    # // ex. /compile_snip/1
    url(r'^compile_snip/(?P<snip_id>[0-9]+)/$', views.compile_snip, name='compile_snip'),
]

pastebinapp/models.py
from django import forms
from django.db import models
from django.forms import ModelForm

from djchoices import DjangoChoices, ChoiceItem

from pastebinapp.widgets import CodeInputWidget

from compile_lang import SUPPORTED_LANGUAGES


# Create your models here.

class Snippet(models.Model):
    class LangType(DjangoChoices):
        C = ChoiceItem('C')
        CPP = ChoiceItem('C++')
        PYTHON = ChoiceItem('PYTHON')
        RUST = ChoiceItem('RUST')
    app_to_pb_comp_lang_map = {
      LangType.C: SUPPORTED_LANGUAGES.C,
      LangType.CPP: SUPPORTED_LANGUAGES.CPP,
      LangType.RUST: SUPPORTED_LANGUAGES.RUST,
      LangType.PYTHON: SUPPORTED_LANGUAGES.PYTHON,
    }
    text = models.TextField(max_length=20000)
    lang = models.CharField(max_length=50,
                            choices=LangType.choices,
                            default=LangType.C)
    title = models.CharField(max_length=100,
                             default='None')

    def compile(self):
        return True

    def __str__(self):
        return '{}: {}'.format(self.title, self.text)

class SnippetForm(ModelForm):
    class Meta:
        model = Snippet
        fields = ['text', 'lang', 'title']
        widgets = {
            'text': CodeInputWidget()
        }

pastebinapp/views.py
from django.shortcuts import get_object_or_404, render
from django.db.utils import ProgrammingError

from django.http import HttpResponse, HttpResponseRedirect, Http404

from .models import Snippet, SnippetForm
from compile_lang import C_Compiler, CPP_Compiler, CompilerException, Rust_Compiler
from .tasks import test, fwd_req

import html
import os
import tempfile
import time

def index(request): 
    latest = Snippet.objects.order_by('pk').reverse()[0:5]
    context = {
      'latest_snips': latest
    }
    return render(request, 'pastebinapp/index.html', context)

def code(request, snip_id):
    try:
        snip = Snippet.objects.get(pk=snip_id)
    except Snippet.DoesNotExist:
        raise Http404("Snippet does not exist")
    return render(request, 'pastebinapp/code.html', 
                  {'code': snip.text, 'title': snip.title,
                   'snip_id': snip_id, 'lang': snip.lang})

def enter_snip(request):
    if request.method == 'POST':
        form = SnippetForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/pastebinapp/')
    else:
        form = SnippetForm()

    return render(request, 'pastebinapp/enter_snip.html', {'form': form})

def compile_snip(request, snip_id):
    try:
        snip = Snippet.objects.get(pk=snip_id)
    except Snippet.DoesNotExist:
        raise Http404("Snippet does not exist")
    print('forwarding')
    result = fwd_req(Snippet.app_to_pb_comp_lang_map[snip.lang],
                     snip.text)
    if result is None:
      print('compiler unavailable')
      return render(request, 'pastebinapp/failure.html', {'message': 'compiler unavailable'})
    print(result)
    return render(request, 'pastebinapp/success.html')

def edit_snip(request, snip_id):
    snip = get_object_or_404(Snippet, pk=snip_id)
    if request.method == 'POST':
        form = SnippetForm(request.POST, instance=snip)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/pastebinapp/')
    else:
        form = SnippetForm(instance=snip)

    return render(request, 'pastebinapp/enter_snip.html', {'form': form})

pastebinapp/templates/pastebinapp/code.html
{% load staticfiles %}
<head>
  <title> {{ title }} </title>
</head>
<body>
  <link href="{% static 'pastebinapp/CodeMirror/lib/codemirror.css' %}" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/lib/codemirror.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/addon/mode/simple.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/mode/clike/clike.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/mode/rust/rust.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/mode/python/python.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/scripts/pastebin2CodeMirror.js' %}"></script>
  <h3>{{ title }}</h3>
  <div id="codedisplay"></div>
  <a href="{% url 'pastebinapp:edit_snip' snip_id %}">Edit</a>
  <a href="{% url 'pastebinapp:compile_snip' snip_id %}">Compile</a>
</body>
<script>
    var lang = "{{ lang|safe }}";
    var mode = langtype2mode(lang);
    console.log(mode);
    function escapenewline(input) {
        var prev = 0;
        var end = 0;
        var newstr = "";
        var remainder = input[0];
        while(end >= 0 )
        {
            var start = remainder.indexOf('"');
            newstr += remainder.slice(0, start + 1);
            remainder = remainder.slice(start + 1);
            end = remainder.indexOf('"');
            prev = end + 1;
            substr = remainder.slice(0, end + 1);
            remainder = remainder.slice(end + 1);
            substr = substr.replace(/\n/g, '\\n');
            newstr += substr;
        }
        newstr += remainder;
        return newstr;
    }
    var code = escapenewline`{{ code|safe }}`;
    var myCodeMirror = CodeMirror(document.getElementById("codedisplay"), {value: code, mode: mode});
</script>

pastebinapp/templates/pastebinapp/enter_snip.html
{% load staticfiles %}
<head>
  <title> Add Code Snippet </title>
</head>
<body>
  <link href="{% static 'pastebinapp/CodeMirror/lib/codemirror.css' %}" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/lib/codemirror.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/addon/mode/simple.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/mode/clike/clike.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/mode/rust/rust.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/CodeMirror/mode/python/python.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/scripts/pastebin2CodeMirror.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/scripts/pastebin2CodeMirror.js' %}"></script>
  <script type="text/javascript" src="{% static 'pastebinapp/scripts/jquery.js' %}"></script>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
<script>
  var mode = langtype2mode($("#id_lang option:selected").text());
  var myCodeMirror = CodeMirror.fromTextArea(document.getElementById("id_text"), {mode: mode});
  $("#id_lang").click(function() {
    mode = langtype2mode($("#id_lang option:selected").text());
    myCodeMirror.setOption("mode", mode);
    myCodeMirror.refresh();
  });
</script>
</body>

pastebinapp/templates/pastebinapp/failure.html
FAILURE!

<p>{{ message }}</p>

pastebinapp/templates/pastebinapp/index.html
<a href="{% url 'pastebinapp:enter_snip' %}">Add new snippet</a>
<br>
{% if latest_snips %}
  {% for snip in latest_snips %}
    <a href="{% url 'pastebinapp:code' snip.pk %}">{{ snip.title }}</a>
    <br>
  {% endfor %}
{% else %}
  <p>No snippets available</p>
{% endif %}

pastebinapp/templates/pastebinapp/success.html
SUCCESS!